/**
 * Gale-Shapley (Hospital-Resident) Algorithm Service
 * 
 * Implements the stable matching algorithm for faculty allocation.
 * Groups are the "proposing" side (residents), faculty are "receiving" (hospitals).
 * 
 * Properties guaranteed:
 *  - Termination: always stops in finite rounds
 *  - Stability: no blocking pair exists
 *  - Group-optimal: best possible stable match for each group
 *  - Completeness: every matchable group gets matched
 */

const mongoose = require('mongoose');
const Group = require('../models/Group');
const Faculty = require('../models/Faculty');
const FacultyPreference = require('../models/FacultyPreference');
const FacultyRanking = require('../models/FacultyRanking');
const AllocationRun = require('../models/AllocationRun');
const SystemConfig = require('../models/SystemConfig');

// ============================================================
// Pre-Algorithm Validation
// ============================================================

/**
 * Validate all pre-conditions before running the algorithm.
 * Returns a validation report with details about eligible groups,
 * faculty participation, and capacity analysis.
 */
async function validatePreRunConditions(semester, academicYear) {
    const report = {
        totalGroups: 0,
        validGroups: 0,
        excludedGroups: [],
        totalFaculty: 0,
        facultyWithRankings: 0,
        facultyWithoutRankings: 0,
        totalCapacity: 0,
        capacityWarning: null,
        isReady: true,
        errors: []
    };

    // 1. Get all finalized groups with preferences for this semester
    const groups = await Group.find({
        semester,
        academicYear,
        status: 'finalized'
    }).populate('members.student', 'fullName studentId');

    report.totalGroups = groups.length;

    // 2. Validate each group
    const validGroupIds = [];
    for (const group of groups) {
        const activeMembers = group.members.filter(m => m.isActive);

        // Check group has enough members
        if (activeMembers.length < (group.minMembers || 2)) {
            report.excludedGroups.push({
                group: group._id,
                name: group.name,
                reason: `Insufficient members (${activeMembers.length}/${group.minMembers || 2})`
            });
            continue;
        }

        // Check group has submitted faculty preferences
        const prefs = await FacultyPreference.findOne({
            student: activeMembers[0].student,
            semester,
            academicYear,
            status: { $ne: 'cancelled' }
        });

        if (!prefs || !prefs.preferences || prefs.preferences.length === 0) {
            report.excludedGroups.push({
                group: group._id,
                name: group.name,
                reason: 'No faculty preferences submitted'
            });
            continue;
        }

        validGroupIds.push(group._id);
    }

    report.validGroups = validGroupIds.length;

    // 3. Get faculty who are listed in at least one group's preferences
    const defaultCapacity = await SystemConfig.getConfigValue('sem5.allocation.defaultFacultyCapacity', 4);

    const allFaculty = await Faculty.find({
        isRetired: false,
        mode: { $in: ['Regular', 'Adjunct', 'On Lien'] }
    });

    report.totalFaculty = allFaculty.length;

    // Count faculty rankings
    const rankings = await FacultyRanking.find({ semester, academicYear });
    const rankedFacultyIds = new Set(rankings.map(r => r.faculty.toString()));

    report.facultyWithRankings = rankings.filter(r => !r.isAutoGenerated).length;
    report.facultyWithoutRankings = allFaculty.length - report.facultyWithRankings;

    // 4. Calculate total capacity
    let totalCapacity = 0;
    for (const fac of allFaculty) {
        const cap = fac.mentorCapacity !== null && fac.mentorCapacity !== undefined
            ? fac.mentorCapacity
            : defaultCapacity;
        totalCapacity += cap;
    }
    report.totalCapacity = totalCapacity;

    // 5. Capacity warning
    if (report.validGroups > totalCapacity) {
        const deficit = report.validGroups - totalCapacity;
        report.capacityWarning = `Capacity shortage: ${report.validGroups} groups but only ${totalCapacity} slots. At least ${deficit} group(s) will require manual allocation.`;
    }

    // 6. Check errors
    if (report.validGroups === 0) {
        report.isReady = false;
        report.errors.push('No valid groups found for allocation');
    }

    return report;
}

// ============================================================
// Tiebreak Helpers
// ============================================================

/**
 * Sort groups by tiebreak method.
 * Used for unranked groups in a faculty's preference list.
 */
function applyTiebreak(groups, method) {
    switch (method) {
        case 'random':
            // Fisher-Yates shuffle
            const shuffled = [...groups];
            for (let i = shuffled.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
            }
            return shuffled;

        case 'alphabetical':
            return [...groups].sort((a, b) => {
                const nameA = a.name || '';
                const nameB = b.name || '';
                return nameA.localeCompare(nameB);
            });

        case 'timestamp':
        default:
            // Sort by creation timestamp (earliest first = higher priority)
            return [...groups].sort((a, b) => {
                const dateA = a.createdAt || new Date(0);
                const dateB = b.createdAt || new Date(0);
                return dateA - dateB;
            });
    }
}

// ============================================================
// Auto-generate Faculty Rankings
// ============================================================

/**
 * For faculty who did not submit rankings, auto-generate rankings
 * using the configured tiebreak method.
 */
async function autoGenerateFacultyRankings(semester, academicYear, tiebreakMethod) {
    const autoGenerated = [];

    // Get all faculty listed in any group's preferences
    const allPrefs = await FacultyPreference.find({
        semester,
        academicYear,
        status: { $ne: 'cancelled' }
    });

    // Build a map: facultyId → [groupIds that listed them]
    const facultyToGroups = new Map();
    for (const pref of allPrefs) {
        for (const p of pref.preferences) {
            const facId = p.faculty.toString();
            if (!facultyToGroups.has(facId)) {
                facultyToGroups.set(facId, []);
            }
            // We store the group info; we'll de-duplicate later
            // For now, store student's group reference
        }
    }

    // Get all groups with preferences - build group → faculty prefs map
    const groups = await Group.find({
        semester,
        academicYear,
        status: 'finalized'
    });

    const groupMap = new Map();
    for (const g of groups) {
        groupMap.set(g._id.toString(), g);
    }

    // Re-build: which faculty are listed by which groups?
    // We need to find group IDs from FacultyPreference records
    const facultyGroupMap = new Map();

    for (const pref of allPrefs) {
        // Find which group this student belongs to
        const studentGroup = groups.find(g =>
            g.members.some(m => m.student.toString() === pref.student.toString() && m.isActive)
        );

        if (!studentGroup) continue;

        for (const p of pref.preferences) {
            const facId = p.faculty.toString();
            if (!facultyGroupMap.has(facId)) {
                facultyGroupMap.set(facId, new Set());
            }
            facultyGroupMap.get(facId).add(studentGroup._id.toString());
        }
    }

    // For each faculty that has groups but no ranking, auto-generate
    for (const [facId, groupIdSet] of facultyGroupMap) {
        const existing = await FacultyRanking.findOne({
            faculty: facId,
            semester,
            academicYear,
            isAutoGenerated: false,
            submittedAt: { $ne: null }
        });

        if (existing) continue; // Faculty submitted manually, skip

        // Get the group documents for tiebreaking
        const groupIds = Array.from(groupIdSet);
        const groupDocs = groupIds.map(id => groupMap.get(id)).filter(Boolean);

        // Apply tiebreak to get ranked order
        const sorted = applyTiebreak(groupDocs, tiebreakMethod);

        const rankedGroups = sorted.map((g, idx) => ({
            group: g._id,
            rank: idx + 1
        }));

        // Upsert the auto-generated ranking
        await FacultyRanking.findOneAndUpdate(
            { faculty: facId, semester, academicYear },
            {
                faculty: facId,
                semester,
                academicYear,
                rankedGroups,
                isAutoGenerated: true,
                submittedAt: new Date()
            },
            { upsert: true, new: true }
        );

        autoGenerated.push(facId);
    }

    return autoGenerated;
}

// ============================================================
// Build Preference Maps
// ============================================================

/**
 * Build the data structures needed by the Gale-Shapley algorithm.
 * 
 * Returns:
 *   groupPrefs: Map<groupId, [facultyId, ...]>  (ordered list)
 *   facultyPrefs: Map<facultyId, Map<groupId, rank>>  (rank lookup)
 *   facultyCapacities: Map<facultyId, number>
 *   groupInfo: Map<groupId, groupDoc>
 *   facultyInfo: Map<facultyId, facultyDoc>
 */
async function buildPreferenceMaps(semester, academicYear) {
    const defaultCapacity = await SystemConfig.getConfigValue('sem5.allocation.defaultFacultyCapacity', 4);

    // 1. Get all valid groups
    const groups = await Group.find({
        semester,
        academicYear,
        status: 'finalized'
    });

    const groupMap = new Map();
    for (const g of groups) {
        groupMap.set(g._id.toString(), g);
    }

    // 2. Build group preference lists
    // Each group's preferences come from FacultyPreference (the student who is group leader)
    const groupPrefs = new Map();

    const allFacPrefs = await FacultyPreference.find({
        semester,
        academicYear,
        status: { $ne: 'cancelled' }
    }).sort({ 'preferences.priority': 1 });

    for (const pref of allFacPrefs) {
        // Find which group this student belongs to
        const studentGroup = groups.find(g =>
            g.members.some(m => m.student.toString() === pref.student.toString() && m.isActive)
        );

        if (!studentGroup) continue;

        const groupId = studentGroup._id.toString();

        // Only process one FacultyPreference per group (first one found)
        if (groupPrefs.has(groupId)) continue;

        // Sort preferences by priority and extract faculty IDs
        const sortedPrefs = [...pref.preferences]
            .sort((a, b) => a.priority - b.priority)
            .map(p => p.faculty.toString());

        groupPrefs.set(groupId, sortedPrefs);
    }

    // 3. Build faculty ranking maps and capacities
    const facultyPrefs = new Map();
    const facultyCapacities = new Map();
    const facultyInfo = new Map();

    const allFaculty = await Faculty.find({
        isRetired: false,
        mode: { $in: ['Regular', 'Adjunct', 'On Lien'] }
    });

    for (const fac of allFaculty) {
        const facId = fac._id.toString();
        facultyInfo.set(facId, fac);

        const cap = fac.mentorCapacity !== null && fac.mentorCapacity !== undefined
            ? fac.mentorCapacity
            : defaultCapacity;
        facultyCapacities.set(facId, cap);
    }

    // Load faculty rankings
    const allRankings = await FacultyRanking.find({ semester, academicYear });

    for (const ranking of allRankings) {
        const facId = ranking.faculty.toString();
        const rankMap = new Map();

        for (const rg of ranking.rankedGroups) {
            rankMap.set(rg.group.toString(), rg.rank);
        }

        facultyPrefs.set(facId, rankMap);
    }

    return { groupPrefs, facultyPrefs, facultyCapacities, groupInfo: groupMap, facultyInfo };
}

// ============================================================
// Core Gale-Shapley Algorithm
// ============================================================

/**
 * Run the Gale-Shapley (Hospital-Resident) algorithm.
 * 
 * @param {Map} groupPrefs - Map<groupId, [facultyId, ...]>
 * @param {Map} facultyPrefs - Map<facultyId, Map<groupId, rank>>
 * @param {Map} facultyCapacities - Map<facultyId, capacity>
 * 
 * @returns {{ matches: Map<groupId, {faculty, round, prefRank}>, adminPool: string[], totalRounds: number }}
 */
function runGaleShapley(groupPrefs, facultyPrefs, facultyCapacities) {
    // State tracking
    const proposalPointer = new Map(); // groupId → next index to propose
    const facultyHolds = new Map();     // facultyId → Set of held groupIds
    const groupMatch = new Map();       // groupId → facultyId (current tentative match)
    const adminPool = [];               // groups that exhausted all preferences
    const matchRound = new Map();       // groupId → round when matched

    // Initialize
    for (const [groupId] of groupPrefs) {
        proposalPointer.set(groupId, 0);
    }
    for (const [facId] of facultyCapacities) {
        facultyHolds.set(facId, new Set());
    }

    let round = 0;
    const MAX_ROUNDS = 1000; // Safety cap (should never be reached)

    while (round < MAX_ROUNDS) {
        round++;
        let proposalsMade = false;

        // Step 2: Every unmatched group with remaining preferences proposes
        const proposals = new Map(); // facultyId → [groupId, ...]

        for (const [groupId, prefList] of groupPrefs) {
            // Skip if already matched or in admin pool
            if (groupMatch.has(groupId)) continue;
            if (adminPool.includes(groupId)) continue;

            const pointer = proposalPointer.get(groupId);

            // No more preferences → admin pool
            if (pointer >= prefList.length) {
                adminPool.push(groupId);
                continue;
            }

            const targetFaculty = prefList[pointer];

            // Check if faculty has capacity 0 → skip immediately
            const cap = facultyCapacities.get(targetFaculty) || 0;
            if (cap === 0) {
                proposalPointer.set(groupId, pointer + 1);
                // Don't count this as a "proposal" that changes state meaningfully
                // but do loop again
                proposalsMade = true;
                continue;
            }

            if (!proposals.has(targetFaculty)) {
                proposals.set(targetFaculty, []);
            }
            proposals.get(targetFaculty).push(groupId);
            proposalsMade = true;
        }

        if (!proposalsMade) break; // Termination condition

        // Step 3: Faculty evaluate proposals
        for (const [facId, newProposals] of proposals) {
            const currentHolds = facultyHolds.get(facId) || new Set();
            const capacity = facultyCapacities.get(facId) || 0;
            const facRanking = facultyPrefs.get(facId) || new Map();

            // Combine current holds + new proposals
            const candidatePool = new Set([...currentHolds, ...newProposals]);

            // Rank all candidates
            const ranked = Array.from(candidatePool).sort((a, b) => {
                const rankA = facRanking.get(a);
                const rankB = facRanking.get(b);

                // Ranked beats unranked
                if (rankA !== undefined && rankB === undefined) return -1;
                if (rankA === undefined && rankB !== undefined) return 1;

                // Both ranked: lower rank number = better
                if (rankA !== undefined && rankB !== undefined) return rankA - rankB;

                // Both unranked: maintain original order (stable)
                return 0;
            });

            // Keep top [capacity], reject rest
            const accepted = new Set(ranked.slice(0, capacity));
            const rejected = ranked.slice(capacity);

            // Update holds
            facultyHolds.set(facId, accepted);

            // Process accepted groups
            for (const gId of accepted) {
                if (!groupMatch.has(gId)) {
                    // Newly matched
                    groupMatch.set(gId, facId);
                    matchRound.set(gId, round);
                }
            }

            // Process rejections
            for (const gId of rejected) {
                if (groupMatch.has(gId) && groupMatch.get(gId) === facId) {
                    // Was held but bumped
                    groupMatch.delete(gId);
                    matchRound.delete(gId);
                }
                // Advance proposal pointer
                const currentPointer = proposalPointer.get(gId);
                proposalPointer.set(gId, currentPointer + 1);
            }
        }

        // Step 5: Check termination
        let allSettled = true;
        for (const [groupId] of groupPrefs) {
            if (!groupMatch.has(groupId) && !adminPool.includes(groupId)) {
                const pointer = proposalPointer.get(groupId);
                if (pointer < groupPrefs.get(groupId).length) {
                    allSettled = false;
                    break;
                } else {
                    // Exhausted preferences
                    if (!adminPool.includes(groupId)) {
                        adminPool.push(groupId);
                    }
                }
            }
        }

        if (allSettled) break;
    }

    // Build final matches
    const matches = new Map();
    for (const [groupId, facId] of groupMatch) {
        const prefList = groupPrefs.get(groupId) || [];
        const prefRank = prefList.indexOf(facId) + 1; // 1-indexed
        matches.set(groupId, {
            faculty: facId,
            round: matchRound.get(groupId) || round,
            prefRank
        });
    }

    return { matches, adminPool, totalRounds: round };
}

// ============================================================
// Main Execution Orchestrator
// ============================================================

/**
 * Full allocation pipeline:
 *  1. Validate pre-conditions
 *  2. Auto-generate rankings for non-submitting faculty
 *  3. Build preference maps
 *  4. Run Gale-Shapley
 *  5. Save results to AllocationRun
 */
async function executeAllocation(semester, academicYear, adminUserId) {
    // Check for existing active run
    const existingRun = await AllocationRun.getActiveRun(semester, academicYear);
    if (existingRun && existingRun.status === 'running') {
        throw new Error('An allocation is already running for this semester');
    }

    // Create or reuse run document
    let run;
    if (existingRun && existingRun.canRerun()) {
        run = existingRun;
        run.status = 'running';
        run.results = [];
        run.adminPool = [];
        run.errorMessage = null;
    } else {
        run = new AllocationRun({
            semester,
            academicYear,
            status: 'running'
        });
    }

    try {
        // Step 1: Load config
        const config = {
            defaultFacultyCapacity: await SystemConfig.getConfigValue('sem5.allocation.defaultFacultyCapacity', 4),
            minGroupPreferences: await SystemConfig.getConfigValue('sem5.allocation.minGroupPreferences', 3),
            maxGroupPreferences: await SystemConfig.getConfigValue('sem5.allocation.maxGroupPreferences', 7),
            tiebreakMethod: await SystemConfig.getConfigValue('sem5.allocation.tiebreakMethod', 'timestamp'),
            autoRankUnsubmittedFaculty: await SystemConfig.getConfigValue('sem5.allocation.autoRankUnsubmittedFaculty', true)
        };
        run.config = config;

        // Step 2: Validate
        const validation = await validatePreRunConditions(semester, academicYear);
        run.validationReport = validation;

        if (!validation.isReady) {
            run.status = 'failed';
            run.errorMessage = validation.errors.join('; ');
            await run.save();
            return run;
        }

        // Step 3: Auto-generate faculty rankings if enabled
        if (config.autoRankUnsubmittedFaculty) {
            await autoGenerateFacultyRankings(semester, academicYear, config.tiebreakMethod);
        }

        // Step 4: Build preference maps
        const { groupPrefs, facultyPrefs, facultyCapacities, groupInfo, facultyInfo } =
            await buildPreferenceMaps(semester, academicYear);

        // Step 5: Run the algorithm
        const { matches, adminPool, totalRounds } =
            runGaleShapley(groupPrefs, facultyPrefs, facultyCapacities);

        // Step 6: Populate results
        run.runAt = new Date();
        run.totalGroups = groupPrefs.size;
        run.matchedGroups = matches.size;
        run.adminPoolGroups = adminPool.length;
        run.totalRounds = totalRounds;
        run.totalCapacity = Array.from(facultyCapacities.values()).reduce((sum, c) => sum + c, 0);

        // Save matched results
        run.results = [];
        for (const [groupId, match] of matches) {
            run.results.push({
                group: new mongoose.Types.ObjectId(groupId),
                faculty: new mongoose.Types.ObjectId(match.faculty),
                matchedRound: match.round,
                preferenceRank: match.prefRank,
                allocatedBy: 'algorithm'
            });
        }

        // Save admin pool
        run.adminPool = adminPool.map(groupId => ({
            group: new mongoose.Types.ObjectId(groupId),
            reason: 'preferences_exhausted'
        }));

        // Add excluded groups to admin pool
        if (run.validationReport && run.validationReport.excludedGroups) {
            for (const excl of run.validationReport.excludedGroups) {
                run.adminPool.push({
                    group: excl.group,
                    reason: 'excluded'
                });
            }
        }

        run.status = 'preview';
        await run.save();

        return run;

    } catch (error) {
        run.status = 'failed';
        run.errorMessage = error.message;
        await run.save();
        throw error;
    }
}

/**
 * Confirm allocation results — makes them visible to all parties.
 * 
 * Note: We avoid MongoDB transactions here so the code works on
 * standalone (non-replica-set) development instances.  The operations
 * are individually idempotent and can be retried safely.
 */
async function confirmAllocation(runId, adminUserId) {
    const run = await AllocationRun.findById(runId);
    if (!run) throw new Error('Allocation run not found');
    if (!run.canConfirm()) throw new Error('Allocation run cannot be confirmed in its current state');

    try {
        // 1. Update run status
        run.status = 'confirmed';
        run.confirmedAt = new Date();
        run.confirmedBy = adminUserId;
        await run.save();

        // 2. Update FacultyPreference and Project records for each matched group
        for (const result of run.results) {
            // Update FacultyPreference for the specific group
            await FacultyPreference.updateOne(
                {
                    group: result.group,
                    semester: run.semester,
                    academicYear: run.academicYear,
                    status: { $ne: 'cancelled' }
                },
                {
                    $set: {
                        status: 'allocated',
                        allocatedFaculty: result.faculty,
                        allocatedBy: result.allocatedBy === 'admin' ? 'admin_allocation' : 'faculty_choice',
                        allocatedAt: new Date()
                    }
                }
            );

            // Update the Project's allocated faculty
            const Project = require('../models/Project');
            await Project.updateOne(
                { group: result.group, semester: run.semester, academicYear: run.academicYear },
                {
                    $set: {
                        faculty: result.faculty,
                        status: 'faculty_allocated',
                        allocatedBy: result.allocatedBy === 'admin' ? 'admin_allocation' : 'faculty_choice'
                    }
                }
            );

            // Update the Group's allocated faculty
            await Group.updateOne(
                { _id: result.group },
                {
                    $set: {
                        allocatedFaculty: result.faculty,
                        allocationStatus: 'allocated'
                    }
                }
            );

            // Increment faculty mentor count
            await Faculty.findByIdAndUpdate(
                result.faculty,
                { $inc: { currentMentorCount: 1 } }
            );
        }

        return run;

    } catch (error) {
        // If something fails mid-way, mark run as failed so admin can retry
        run.status = 'failed';
        run.errorMessage = `Confirmation failed: ${error.message}`;
        await run.save();
        throw error;
    }
}

/**
 * Reset allocation to allow re-run.
 */
async function resetAllocation(runId) {
    const run = await AllocationRun.findById(runId);
    if (!run) throw new Error('Allocation run not found');
    if (run.status === 'confirmed') throw new Error('Cannot reset a confirmed allocation');

    run.status = 'not_run';
    run.results = [];
    run.adminPool = [];
    run.runAt = null;
    run.totalRounds = 0;
    run.matchedGroups = 0;
    run.adminPoolGroups = 0;
    run.errorMessage = null;
    await run.save();

    return run;
}

/**
 * Manually assign faculty to an admin pool group.
 */
async function assignAdminPoolGroup(runId, groupId, facultyId, adminUserId) {
    const run = await AllocationRun.findById(runId);
    if (!run) throw new Error('Allocation run not found');

    const poolEntry = run.adminPool.find(p => p.group.toString() === groupId);
    if (!poolEntry) throw new Error('Group not found in admin pool');

    // Check faculty has remaining capacity
    const defaultCapacity = await SystemConfig.getConfigValue('sem5.allocation.defaultFacultyCapacity', 4);
    const faculty = await Faculty.findById(facultyId);
    if (!faculty) throw new Error('Faculty not found');

    const cap = faculty.mentorCapacity !== null && faculty.mentorCapacity !== undefined
        ? faculty.mentorCapacity
        : defaultCapacity;

    // Count current assignments for this faculty in this run
    const currentAssignments = run.results.filter(r => r.faculty.toString() === facultyId).length;
    const poolAssignments = run.adminPool.filter(
        p => p.assignedFaculty && p.assignedFaculty.toString() === facultyId
    ).length;

    if (currentAssignments + poolAssignments >= cap) {
        throw new Error('Faculty has reached their maximum capacity');
    }

    // Update pool entry
    poolEntry.assignedFaculty = facultyId;
    poolEntry.assignedAt = new Date();
    poolEntry.assignedBy = adminUserId;

    // Also add to results array for consistency
    run.results.push({
        group: new mongoose.Types.ObjectId(groupId),
        faculty: new mongoose.Types.ObjectId(facultyId),
        matchedRound: 0,
        preferenceRank: 0,
        allocatedBy: 'admin'
    });

    run.matchedGroups = run.results.length;
    run.adminPoolGroups = run.adminPool.filter(p => !p.assignedFaculty).length;

    await run.save();
    return run;
}

module.exports = {
    validatePreRunConditions,
    autoGenerateFacultyRankings,
    buildPreferenceMaps,
    runGaleShapley,
    executeAllocation,
    confirmAllocation,
    resetAllocation,
    assignAdminPoolGroup,
    applyTiebreak
};
