/**
 * Allocation Controller
 * 
 * Handles all REST endpoints for the Gale-Shapley faculty allocation system.
 * Endpoints are organized by role: Admin, Student, Faculty.
 */

const mongoose = require('mongoose');
const AllocationRun = require('../models/AllocationRun');
const FacultyRanking = require('../models/FacultyRanking');
const FacultyPreference = require('../models/FacultyPreference');
const Faculty = require('../models/Faculty');
const Group = require('../models/Group');
const Student = require('../models/Student');
const SystemConfig = require('../models/SystemConfig');
const allocationService = require('../services/allocationService');

// ====================================================
// Helper: Get current academic year
// ====================================================
async function getCurrentAcademicYear() {
    return await SystemConfig.getConfigValue('academic.currentYear', '2025-26');
}

// Helper: Check if a date window is currently open
function isWindowOpen(windowConfig) {
    if (!windowConfig || !windowConfig.start || !windowConfig.end) return false;
    const now = new Date();
    return now >= new Date(windowConfig.start) && now <= new Date(windowConfig.end);
}

function getWindowStatus(windowConfig) {
    if (!windowConfig || !windowConfig.start || !windowConfig.end) {
        return { status: 'not_configured', start: null, end: null };
    }
    const now = new Date();
    const start = new Date(windowConfig.start);
    const end = new Date(windowConfig.end);

    if (now < start) return { status: 'upcoming', start, end };
    if (now > end) return { status: 'closed', start, end };
    return { status: 'open', start, end };
}

// ====================================================
// ADMIN ENDPOINTS
// ====================================================

/**
 * GET /allocation/admin/config
 * Get current allocation configuration
 */
exports.getConfig = async (req, res) => {
    try {
        const semester = parseInt(req.query.semester) || 5;
        const academicYear = req.query.academicYear || await getCurrentAcademicYear();

        const config = {
            minGroupPreferences: await SystemConfig.getConfigValue('sem5.allocation.minGroupPreferences', 3),
            maxGroupPreferences: await SystemConfig.getConfigValue('sem5.allocation.maxGroupPreferences', 7),
            defaultFacultyCapacity: await SystemConfig.getConfigValue('sem5.allocation.defaultFacultyCapacity', 4),
            tiebreakMethod: await SystemConfig.getConfigValue('sem5.allocation.tiebreakMethod', 'timestamp'),
            autoRankUnsubmittedFaculty: await SystemConfig.getConfigValue('sem5.allocation.autoRankUnsubmittedFaculty', true),
            showDemandIndicators: await SystemConfig.getConfigValue('sem5.allocation.showDemandIndicators', true),
            groupPreferenceWindow: await SystemConfig.getConfigValue('sem5.allocation.groupPreferenceWindow', { start: null, end: null }),
            facultyRankingWindow: await SystemConfig.getConfigValue('sem5.allocation.facultyRankingWindow', { start: null, end: null })
        };

        // Get current run status
        const latestRun = await AllocationRun.getLatestRun(semester, academicYear);

        // Get statistics
        const totalGroups = await Group.countDocuments({ semester, academicYear, status: 'finalized' });
        const totalFaculty = await Faculty.countDocuments({ isRetired: false });
        const defaultCap = config.defaultFacultyCapacity;

        let totalCapacity = 0;
        const faculty = await Faculty.find({ isRetired: false });
        for (const f of faculty) {
            totalCapacity += (f.mentorCapacity !== null && f.mentorCapacity !== undefined) ? f.mentorCapacity : defaultCap;
        }

        // Count submissions
        const groupPrefsSubmitted = await FacultyPreference.countDocuments({
            semester, academicYear, status: { $ne: 'cancelled' },
            'preferences.0': { $exists: true }
        });
        const facultyRankingsSubmitted = await FacultyRanking.countDocuments({
            semester, academicYear, isAutoGenerated: false, submittedAt: { $ne: null }
        });

        res.json({
            success: true,
            data: {
                config,
                statistics: {
                    totalGroups,
                    totalFaculty,
                    totalCapacity,
                    groupPrefsSubmitted,
                    facultyRankingsSubmitted,
                    capacityDeficit: Math.max(0, totalGroups - totalCapacity)
                },
                latestRun: latestRun ? {
                    _id: latestRun._id,
                    status: latestRun.status,
                    runAt: latestRun.runAt,
                    confirmedAt: latestRun.confirmedAt,
                    totalGroups: latestRun.totalGroups,
                    matchedGroups: latestRun.matchedGroups,
                    adminPoolGroups: latestRun.adminPoolGroups,
                    totalRounds: latestRun.totalRounds
                } : null,
                windowStatus: {
                    groupPreference: getWindowStatus(config.groupPreferenceWindow),
                    facultyRanking: getWindowStatus(config.facultyRankingWindow)
                }
            }
        });
    } catch (error) {
        console.error('Error getting allocation config:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * PUT /allocation/admin/config
 * Update allocation configuration
 */
exports.updateConfig = async (req, res) => {
    try {
        const updates = req.body;
        const configMap = {
            minGroupPreferences: { key: 'sem5.allocation.minGroupPreferences', type: 'number' },
            maxGroupPreferences: { key: 'sem5.allocation.maxGroupPreferences', type: 'number' },
            defaultFacultyCapacity: { key: 'sem5.allocation.defaultFacultyCapacity', type: 'number' },
            tiebreakMethod: { key: 'sem5.allocation.tiebreakMethod', type: 'string' },
            autoRankUnsubmittedFaculty: { key: 'sem5.allocation.autoRankUnsubmittedFaculty', type: 'boolean' },
            showDemandIndicators: { key: 'sem5.allocation.showDemandIndicators', type: 'boolean' },
            groupPreferenceWindow: { key: 'sem5.allocation.groupPreferenceWindow', type: 'object' },
            facultyRankingWindow: { key: 'sem5.allocation.facultyRankingWindow', type: 'object' }
        };

        for (const [field, value] of Object.entries(updates)) {
            if (configMap[field]) {
                await SystemConfig.setConfigValue(
                    configMap[field].key,
                    value,
                    configMap[field].type,
                    `Allocation config: ${field}`,
                    'sem5',
                    req.user.id
                );
            }
        }

        res.json({ success: true, message: 'Configuration updated successfully' });
    } catch (error) {
        console.error('Error updating allocation config:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * POST /allocation/admin/validate
 * Run pre-algorithm validation
 */
exports.validatePreRun = async (req, res) => {
    try {
        const semester = parseInt(req.body.semester) || 5;
        const academicYear = req.body.academicYear || await getCurrentAcademicYear();

        const report = await allocationService.validatePreRunConditions(semester, academicYear);
        res.json({ success: true, data: report });
    } catch (error) {
        console.error('Error validating pre-run:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * POST /allocation/admin/run
 * Execute the Gale-Shapley algorithm
 */
exports.runAlgorithm = async (req, res) => {
    try {
        const semester = parseInt(req.body.semester) || 5;
        const academicYear = req.body.academicYear || await getCurrentAcademicYear();

        const run = await allocationService.executeAllocation(semester, academicYear, req.user.id);

        // Populate for response
        const populated = await AllocationRun.getLatestRun(semester, academicYear);

        res.json({
            success: true,
            message: run.status === 'preview'
                ? `Algorithm completed in ${run.totalRounds} rounds. ${run.matchedGroups} groups matched, ${run.adminPoolGroups} in admin pool.`
                : `Algorithm run failed: ${run.errorMessage}`,
            data: populated
        });
    } catch (error) {
        console.error('Error running allocation algorithm:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * POST /allocation/admin/confirm
 * Confirm and publish allocation results
 */
exports.confirmResults = async (req, res) => {
    try {
        const { runId } = req.body;
        const run = await allocationService.confirmAllocation(runId, req.user.id);

        res.json({
            success: true,
            message: 'Allocation results confirmed and published',
            data: run
        });
    } catch (error) {
        console.error('Error confirming allocation:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * POST /allocation/admin/reset
 * Reset allocation to allow re-run
 */
exports.resetAllocation = async (req, res) => {
    try {
        const { runId } = req.body;
        const run = await allocationService.resetAllocation(runId);

        res.json({
            success: true,
            message: 'Allocation reset. You can now re-run the algorithm.',
            data: run
        });
    } catch (error) {
        console.error('Error resetting allocation:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/admin/results
 * Get detailed allocation results
 */
exports.getResults = async (req, res) => {
    try {
        const semester = parseInt(req.query.semester) || 5;
        const academicYear = req.query.academicYear || await getCurrentAcademicYear();

        const run = await AllocationRun.getLatestRun(semester, academicYear);
        if (!run) {
            return res.json({ success: true, data: null, message: 'No allocation run found' });
        }

        res.json({ success: true, data: run });
    } catch (error) {
        console.error('Error getting allocation results:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/admin/admin-pool
 * Get unmatched groups from admin pool
 */
exports.getAdminPool = async (req, res) => {
    try {
        const semester = parseInt(req.query.semester) || 5;
        const academicYear = req.query.academicYear || await getCurrentAcademicYear();

        const run = await AllocationRun.getLatestRun(semester, academicYear);
        if (!run) {
            return res.json({ success: true, data: [] });
        }

        // Get unassigned admin pool groups
        const unassigned = run.adminPool.filter(p => !p.assignedFaculty);

        res.json({ success: true, data: { adminPool: run.adminPool, unassigned } });
    } catch (error) {
        console.error('Error getting admin pool:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * POST /allocation/admin/admin-pool/:groupId/assign
 * Manually assign faculty to an admin pool group
 */
exports.assignAdminPoolGroup = async (req, res) => {
    try {
        const { groupId } = req.params;
        const { facultyId, runId } = req.body;

        const run = await allocationService.assignAdminPoolGroup(runId, groupId, facultyId, req.user.id);

        res.json({
            success: true,
            message: 'Faculty assigned to group successfully',
            data: run
        });
    } catch (error) {
        console.error('Error assigning admin pool group:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/admin/faculty-capacity
 * Get all faculty with their capacity info
 */
exports.getFacultyCapacity = async (req, res) => {
    try {
        const semester = parseInt(req.query.semester) || 5;
        const academicYear = req.query.academicYear || await getCurrentAcademicYear();
        const defaultCapacity = await SystemConfig.getConfigValue('sem5.allocation.defaultFacultyCapacity', 4);

        const faculty = await Faculty.find({ isRetired: false }).select('fullName facultyId department mentorCapacity currentMentorCount');

        // Get current run (lightweight — no deep populates)
        const run = await AllocationRun.findOne({ semester, academicYear })
            .sort({ createdAt: -1 })
            .lean();

        const facultyData = faculty.map(f => {
            const cap = (f.mentorCapacity !== null && f.mentorCapacity !== undefined) ? f.mentorCapacity : defaultCapacity;
            let assigned = 0;
            if (run) {
                assigned = run.results.filter(r => r.faculty.toString() === f._id.toString()).length;
                assigned += run.adminPool.filter(p => p.assignedFaculty && p.assignedFaculty.toString() === f._id.toString()).length;
            }
            return {
                _id: f._id,
                fullName: f.fullName,
                facultyId: f.facultyId,
                department: f.department,
                capacity: cap,
                assigned,
                remaining: cap - assigned
            };
        });

        res.json({ success: true, data: facultyData });
    } catch (error) {
        console.error('Error getting faculty capacity:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * PUT /allocation/admin/faculty/:facultyId/capacity
 * Override per-faculty capacity
 */
exports.updateFacultyCapacity = async (req, res) => {
    try {
        const { facultyId } = req.params;
        const { capacity } = req.body;

        const faculty = await Faculty.findById(facultyId);
        if (!faculty) {
            return res.status(404).json({ success: false, message: 'Faculty not found' });
        }

        faculty.mentorCapacity = capacity;
        await faculty.save();

        res.json({ success: true, message: 'Faculty capacity updated', data: faculty });
    } catch (error) {
        console.error('Error updating faculty capacity:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

// ====================================================
// STUDENT ENDPOINTS
// ====================================================

/**
 * GET /allocation/student/config
 * Get preference window config and status for students
 */
exports.getStudentConfig = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();

        const groupPrefWindow = await SystemConfig.getConfigValue('sem5.allocation.groupPreferenceWindow', { start: null, end: null });
        const minPrefs = await SystemConfig.getConfigValue('sem5.allocation.minGroupPreferences', 3);
        const maxPrefs = await SystemConfig.getConfigValue('sem5.allocation.maxGroupPreferences', 7);
        const showDemand = await SystemConfig.getConfigValue('sem5.allocation.showDemandIndicators', true);

        // Check if the allocation has been confirmed (results available)
        const run = await AllocationRun.findOne({
            semester, academicYear, status: 'confirmed'
        });

        res.json({
            success: true,
            data: {
                windowStatus: getWindowStatus(groupPrefWindow),
                minPreferences: minPrefs,
                maxPreferences: maxPrefs,
                showDemandIndicators: showDemand,
                allocationConfirmed: !!run
            }
        });
    } catch (error) {
        console.error('Error getting student config:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/student/preferences
 * Get current group's submitted preferences
 */
exports.getGroupPreferences = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();

        // Find student
        const student = await Student.findOne({ user: req.user.id });
        if (!student) return res.status(404).json({ success: false, message: 'Student not found' });

        // Find student's group
        const group = await Group.findOne({
            semester,
            academicYear,
            'members.student': student._id,
            'members.isActive': true,
            status: 'finalized'
        });

        if (!group) {
            return res.json({ success: true, data: { preferences: [], group: null } });
        }

        // Find the group's project
        const Project = require('../models/Project');
        const project = await Project.findOne({
            semester,
            academicYear,
            group: group._id
        });

        // Get faculty preferences (using the group leader's record)
        const pref = await FacultyPreference.findOne({
            student: student._id,
            semester,
            academicYear,
            status: { $ne: 'cancelled' }
        }).populate('preferences.faculty', 'fullName facultyId department prefix');

        res.json({
            success: true,
            data: {
                group: { _id: group._id, name: group.name },
                project: project ? { _id: project._id, title: project.title, status: project.status } : null,
                preferences: pref ? pref.preferences.sort((a, b) => a.priority - b.priority) : []
            }
        });
    } catch (error) {
        console.error('Error getting group preferences:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * POST /allocation/student/preferences
 * Submit/update ranked faculty preference list
 */
exports.submitGroupPreferences = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();
        const { preferences } = req.body; // Array of { faculty: facultyId, priority: number }

        // Validate window is open
        const window = await SystemConfig.getConfigValue('sem5.allocation.groupPreferenceWindow', { start: null, end: null });
        if (!isWindowOpen(window)) {
            return res.status(400).json({ success: false, message: 'Group preference submission window is not open' });
        }

        // Validate preference count
        const minPrefs = await SystemConfig.getConfigValue('sem5.allocation.minGroupPreferences', 3);
        const maxPrefs = await SystemConfig.getConfigValue('sem5.allocation.maxGroupPreferences', 7);

        if (!preferences || preferences.length < minPrefs) {
            return res.status(400).json({
                success: false,
                message: `Please select at least ${minPrefs} faculty preferences`
            });
        }
        if (preferences.length > maxPrefs) {
            return res.status(400).json({
                success: false,
                message: `Maximum ${maxPrefs} faculty preferences allowed`
            });
        }

        // Find student and their group
        const student = await Student.findOne({ user: req.user.id });
        if (!student) return res.status(404).json({ success: false, message: 'Student not found' });

        const group = await Group.findOne({
            semester,
            academicYear,
            'members.student': student._id,
            'members.isActive': true,
            status: 'finalized'
        });

        if (!group) {
            return res.status(400).json({ success: false, message: 'You must be in a finalized group to submit preferences' });
        }

        // Find the group's project
        const Project = require('../models/Project');
        const project = await Project.findOne({
            semester,
            academicYear,
            group: group._id
        });

        if (!project) {
            return res.status(400).json({ success: false, message: 'You must register a project before submitting faculty preferences' });
        }

        // Check student is leader
        if (group.leader.toString() !== student._id.toString()) {
            return res.status(403).json({ success: false, message: 'Only the group leader can submit faculty preferences' });
        }

        // Find or create FacultyPreference record
        let pref = await FacultyPreference.findOne({
            student: student._id,
            semester,
            academicYear
        });

        const formattedPrefs = preferences.map((p, idx) => ({
            faculty: p.faculty,
            priority: idx + 1
        }));

        if (pref) {
            pref.preferences = formattedPrefs;
            pref.status = 'pending';
            await pref.save();
        } else {
            pref = new FacultyPreference({
                student: student._id,
                project: project._id,
                semester,
                academicYear,
                preferences: formattedPrefs,
                status: 'pending'
            });
            await pref.save();
        }

        res.json({
            success: true,
            message: 'Faculty preferences submitted successfully',
            data: { preferences: formattedPrefs }
        });
    } catch (error) {
        console.error('Error submitting group preferences:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/student/demand
 * Get demand indicators for each faculty
 */
exports.getFacultyDemand = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();

        const showDemand = await SystemConfig.getConfigValue('sem5.allocation.showDemandIndicators', true);
        if (!showDemand) {
            return res.json({ success: true, data: {} });
        }

        // Get all preferences
        const allPrefs = await FacultyPreference.find({
            semester,
            academicYear,
            status: { $ne: 'cancelled' },
            'preferences.0': { $exists: true }
        });

        // Count how many groups listed each faculty
        const demand = {};
        for (const pref of allPrefs) {
            for (const p of pref.preferences) {
                const facId = p.faculty.toString();
                demand[facId] = (demand[facId] || 0) + 1;
            }
        }

        // Count first-choice demand
        const firstChoiceDemand = {};
        for (const pref of allPrefs) {
            const sorted = [...pref.preferences].sort((a, b) => a.priority - b.priority);
            if (sorted.length > 0) {
                const facId = sorted[0].faculty.toString();
                firstChoiceDemand[facId] = (firstChoiceDemand[facId] || 0) + 1;
            }
        }

        res.json({
            success: true,
            data: { totalDemand: demand, firstChoiceDemand }
        });
    } catch (error) {
        console.error('Error getting faculty demand:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/student/status
 * Get allocation result for the student's group (after confirmed)
 */
exports.getStudentAllocationStatus = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();

        const student = await Student.findOne({ user: req.user.id });
        if (!student) return res.status(404).json({ success: false, message: 'Student not found' });

        const group = await Group.findOne({
            semester,
            academicYear,
            'members.student': student._id,
            'members.isActive': true
        });

        if (!group) {
            return res.json({ success: true, data: { status: 'no_group' } });
        }

        // Find confirmed run
        const run = await AllocationRun.findOne({
            semester, academicYear, status: 'confirmed'
        })
            .populate('results.faculty', 'fullName facultyId department prefix')
            .populate('adminPool.assignedFaculty', 'fullName facultyId department prefix');

        if (!run) {
            return res.json({ success: true, data: { status: 'pending', message: 'Allocation in progress — please wait' } });
        }

        // Check if group is in results
        const result = run.results.find(r => r.group.toString() === group._id.toString());
        if (result) {
            return res.json({
                success: true,
                data: {
                    status: 'allocated',
                    faculty: result.faculty,
                    matchedRound: result.matchedRound,
                    preferenceRank: result.preferenceRank,
                    allocatedBy: result.allocatedBy
                }
            });
        }

        // Check if group is in admin pool (assigned)
        const poolEntry = run.adminPool.find(p => p.group.toString() === group._id.toString());
        if (poolEntry && poolEntry.assignedFaculty) {
            return res.json({
                success: true,
                data: {
                    status: 'allocated',
                    faculty: poolEntry.assignedFaculty,
                    allocatedBy: 'admin'
                }
            });
        }

        if (poolEntry) {
            return res.json({
                success: true,
                data: {
                    status: 'admin_pool',
                    message: 'Your group is being reviewed by the admin for manual assignment'
                }
            });
        }

        return res.json({ success: true, data: { status: 'pending' } });
    } catch (error) {
        console.error('Error getting student allocation status:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

// ====================================================
// FACULTY ENDPOINTS
// ====================================================

/**
 * GET /allocation/faculty/groups-to-rank
 * Get groups that listed this faculty in their preferences
 */
exports.getGroupsToRank = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();

        const faculty = await Faculty.findOne({ user: req.user.id });
        if (!faculty) return res.status(404).json({ success: false, message: 'Faculty not found' });

        // Get faculty ranking window status
        const window = await SystemConfig.getConfigValue('sem5.allocation.facultyRankingWindow', { start: null, end: null });

        // Find all groups that listed this faculty
        const prefs = await FacultyPreference.find({
            semester,
            academicYear,
            status: { $ne: 'cancelled' },
            'preferences.faculty': faculty._id
        }).populate('student', 'fullName studentId');

        // Get the groups for these students
        const groupIds = new Set();
        const groupDetails = [];

        for (const pref of prefs) {
            const group = await Group.findOne({
                semester,
                academicYear,
                'members.student': pref.student._id,
                'members.isActive': true,
                status: 'finalized'
            }).populate('members.student', 'fullName studentId');

            if (group && !groupIds.has(group._id.toString())) {
                groupIds.add(group._id.toString());

                // Find the project for this group
                const Project = require('../models/Project');
                const project = await Project.findOne({
                    semester,
                    academicYear,
                    group: group._id
                }).select('title description');

                groupDetails.push({
                    _id: group._id,
                    name: group.name,
                    members: group.members.filter(m => m.isActive).map(m => ({
                        fullName: m.student.fullName,
                        studentId: m.student.studentId,
                        role: m.role
                    })),
                    project: project ? { title: project.title, description: project.description } : null,
                    createdAt: group.createdAt
                });
            }
        }

        // Get existing ranking if any
        const existing = await FacultyRanking.getByFaculty(faculty._id, semester, academicYear);

        res.json({
            success: true,
            data: {
                windowStatus: getWindowStatus(window),
                groups: groupDetails,
                existingRanking: existing ? existing.rankedGroups.sort((a, b) => a.rank - b.rank) : [],
                hasSubmitted: existing ? !existing.isAutoGenerated && !!existing.submittedAt : false,
                submittedAt: existing ? existing.submittedAt : null
            }
        });
    } catch (error) {
        console.error('Error getting groups to rank:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * POST /allocation/faculty/rankings
 * Submit/update ranked group list
 */
exports.submitFacultyRankings = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();
        const { rankings } = req.body; // Array of { group: groupId, rank: number }

        // Validate window is open
        const window = await SystemConfig.getConfigValue('sem5.allocation.facultyRankingWindow', { start: null, end: null });
        if (!isWindowOpen(window)) {
            return res.status(400).json({ success: false, message: 'Faculty ranking submission window is not open' });
        }

        const faculty = await Faculty.findOne({ user: req.user.id });
        if (!faculty) return res.status(404).json({ success: false, message: 'Faculty not found' });

        // Validate no duplicate ranks
        const ranks = rankings.map(r => r.rank);
        if (new Set(ranks).size !== ranks.length) {
            return res.status(400).json({ success: false, message: 'Rankings must have unique rank values' });
        }

        // Format rankings
        const formattedRankings = rankings.map(r => ({
            group: r.group,
            rank: r.rank
        }));

        // Upsert ranking
        await FacultyRanking.findOneAndUpdate(
            { faculty: faculty._id, semester, academicYear },
            {
                faculty: faculty._id,
                semester,
                academicYear,
                rankedGroups: formattedRankings,
                isAutoGenerated: false,
                submittedAt: new Date()
            },
            { upsert: true, new: true }
        );

        // Update faculty submission flag
        faculty.hasSubmittedRankings = true;
        await faculty.save();

        res.json({
            success: true,
            message: 'Group rankings submitted successfully',
            data: { rankings: formattedRankings }
        });
    } catch (error) {
        console.error('Error submitting faculty rankings:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/faculty/status
 * Get faculty allocation status and window info
 */
exports.getFacultyStatus = async (req, res) => {
    try {
        const semester = 5;
        const academicYear = await getCurrentAcademicYear();

        const faculty = await Faculty.findOne({ user: req.user.id });
        if (!faculty) return res.status(404).json({ success: false, message: 'Faculty not found' });

        const window = await SystemConfig.getConfigValue('sem5.allocation.facultyRankingWindow', { start: null, end: null });
        const ranking = await FacultyRanking.getByFaculty(faculty._id, semester, academicYear);

        // Check if allocation is confirmed
        const run = await AllocationRun.findOne({
            semester, academicYear, status: 'confirmed'
        });

        // Get assigned groups if confirmed
        let assignedGroups = [];
        if (run) {
            const myResults = run.results.filter(r => r.faculty.toString() === faculty._id.toString());
            const groupIds = myResults.map(r => r.group);
            assignedGroups = await Group.find({ _id: { $in: groupIds } })
                .populate('members.student', 'fullName studentId')
                .select('name members');
        }

        res.json({
            success: true,
            data: {
                windowStatus: getWindowStatus(window),
                hasSubmitted: ranking ? !ranking.isAutoGenerated && !!ranking.submittedAt : false,
                submittedAt: ranking ? ranking.submittedAt : null,
                rankedCount: ranking ? ranking.rankedGroups.length : 0,
                allocationConfirmed: !!run,
                assignedGroups
            }
        });
    } catch (error) {
        console.error('Error getting faculty status:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * GET /allocation/faculty-list
 * Get all available faculty for student preference selection
 */
exports.getAvailableFaculty = async (req, res) => {
    try {
        const defaultCapacity = await SystemConfig.getConfigValue('sem5.allocation.defaultFacultyCapacity', 4);

        const faculty = await Faculty.find({
            isRetired: false,
            mode: { $in: ['Regular', 'Adjunct', 'On Lien'] }
        }).select('fullName facultyId department prefix designation mentorCapacity');

        // Filter out faculty with 0 capacity
        const available = faculty.filter(f => {
            const cap = (f.mentorCapacity !== null && f.mentorCapacity !== undefined) ? f.mentorCapacity : defaultCapacity;
            return cap > 0;
        });

        res.json({
            success: true,
            data: available.map(f => ({
                _id: f._id,
                fullName: f.fullName,
                facultyId: f.facultyId,
                department: f.department,
                prefix: f.prefix,
                designation: f.designation
            }))
        });
    } catch (error) {
        console.error('Error getting available faculty:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};
