const mongoose = require('mongoose');

const facultyRankingSchema = new mongoose.Schema({
    // Faculty reference
    faculty: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Faculty',
        required: true,
        index: true
    },

    // Semester & Academic Year
    semester: {
        type: Number,
        required: true,
        min: 1,
        max: 8,
        index: true
    },
    academicYear: {
        type: String,
        required: true,
        trim: true
    },

    // Ranked groups (ordered by faculty preference)
    rankedGroups: [{
        group: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Group',
            required: true
        },
        rank: {
            type: Number,
            required: true,
            min: 1
        }
    }],

    // Whether this ranking was auto-generated (faculty didn't submit)
    isAutoGenerated: {
        type: Boolean,
        default: false
    },

    // Submission timestamp
    submittedAt: {
        type: Date,
        default: null
    },

    // Timestamps
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
}, {
    timestamps: true
});

// Compound index for uniqueness
facultyRankingSchema.index({ faculty: 1, semester: 1, academicYear: 1 }, { unique: true });

// Pre-save middleware
facultyRankingSchema.pre('save', function (next) {
    this.updatedAt = Date.now();
    next();
});

// Pre-save: validate ranks are unique and sequential
facultyRankingSchema.pre('save', function (next) {
    if (this.rankedGroups && this.rankedGroups.length > 0) {
        const ranks = this.rankedGroups.map(rg => rg.rank);
        const uniqueRanks = [...new Set(ranks)];
        if (ranks.length !== uniqueRanks.length) {
            return next(new Error('Rankings must have unique rank values'));
        }
    }
    next();
});

// Static: Get rankings by faculty
facultyRankingSchema.statics.getByFaculty = function (facultyId, semester, academicYear) {
    return this.findOne({ faculty: facultyId, semester, academicYear })
        .populate('rankedGroups.group', 'name members semester status');
};

// Static: Get all rankings for a semester
facultyRankingSchema.statics.getAllForSemester = function (semester, academicYear) {
    return this.find({ semester, academicYear })
        .populate('faculty', 'fullName facultyId department mentorCapacity')
        .populate('rankedGroups.group', 'name members semester');
};

// Static: Get faculty who have submitted rankings
facultyRankingSchema.statics.getSubmittedFaculty = function (semester, academicYear) {
    return this.find({
        semester,
        academicYear,
        isAutoGenerated: false,
        submittedAt: { $ne: null }
    }).select('faculty submittedAt');
};

module.exports = mongoose.model('FacultyRanking', facultyRankingSchema);
